name: Generate outputs files

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.12
        with:
          path: $GITHUB_WORKSPACE
          args: --data-dir=./.pandoc --defaults settings.yaml --output=output/julia-cheatsheet.pdf
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
